/** @type {import('tailwindcss').Config} */
// Design tokens reconciled from the Stitch export's 3 consistent screens
// (login / inventory / modals-states) and precision_automate/DESIGN.md.
// The dashboard mockup used a slightly different slate palette; we
// standardize on this one across the whole app per DESIGN.md's stated
// "Electric Blue #2563EB primary" direction.
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#0053db",
        "error-container": "#ffdad6",
        "inverse-surface": "#2e3039",
        "secondary-fixed": "#d3e4fe",
        "primary-fixed-dim": "#b4c5ff",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-container": "#54647a",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container": "#ededf9",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        "secondary-container": "#d0e1fb",
        "surface-bright": "#faf8ff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e1e2ed",
        "on-tertiary-container": "#ffede6",
        "surface-container-lowest": "#ffffff",
        surface: "#faf8ff",
        secondary: "#505f76",
        "surface-container-high": "#e7e7f3",
        "tertiary-fixed-dim": "#ffb596",
        tertiary: "#943700",
        background: "#faf8ff",
        "surface-container-low": "#f3f3fe",
        "secondary-fixed-dim": "#b7c8e1",
        "surface-dim": "#d9d9e5",
        "on-background": "#191b23",
        "tertiary-container": "#bc4800",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f0fb",
        "inverse-primary": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "on-secondary": "#ffffff",
        "on-surface": "#191b23",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#00174b",
        "surface-variant": "#e1e2ed",
        primary: "#2563eb",
        "primary-container": "#dbeafe",
        "on-tertiary-fixed": "#360f00",
        "on-tertiary-fixed-variant": "#7d2d00",
        error: "#ba1a1a",
        "on-surface-variant": "#434655",
        "on-primary-container": "#1e40af",
        success: "#16a34a",
        "success-container": "#dcfce7",
        "on-success-container": "#166534",
        warning: "#d97706",
        "warning-container": "#fef3c7",
        "on-warning-container": "#92400e",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.5rem",
        lg: "0.75rem",
        xl: "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        base: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "24px",
        margin: "32px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "title-lg": ["18px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      boxShadow: {
        card: "0 1px 3px 0 rgba(0,0,0,0.1), 0 1px 2px -1px rgba(0,0,0,0.1)",
        "card-hover": "0 4px 12px 0 rgba(0,0,0,0.10), 0 2px 4px -1px rgba(0,0,0,0.08)",
        modal: "0 20px 60px -12px rgba(15,23,42,0.35)",
      },
    },
  },
  plugins: [],
};
